import { AbstractPlayerSearchInformation } from "./types/common/AbstractPlayerSearchInformation";
import { AccountTagInformation } from "./types/common/AccountTagInformation";
import { StatisticData } from "./types/common/basic/StatisticData";
import { StatisticDataBoolean } from "./types/common/basic/StatisticDataBoolean";
import { StatisticDataByte } from "./types/common/basic/StatisticDataByte";
import { StatisticDataInt } from "./types/common/basic/StatisticDataInt";
import { StatisticDataShort } from "./types/common/basic/StatisticDataShort";
import { StatisticDataString } from "./types/common/basic/StatisticDataString";
import { PlayerSearchCharacterNameInformation } from "./types/common/PlayerSearchCharacterNameInformation";
import { PlayerSearchTagInformation } from "./types/common/PlayerSearchTagInformation";
import { GameServerInformations } from "./types/connection/GameServerInformations";
import { Achievement } from "./types/game/achievement/Achievement";
import { AchievementAchieved } from "./types/game/achievement/AchievementAchieved";
import { AchievementAchievedRewardable } from "./types/game/achievement/AchievementAchievedRewardable";
import { AchievementObjective } from "./types/game/achievement/AchievementObjective";
import { AchievementPioneerRank } from "./types/game/achievement/AchievementPioneerRank";
import { AchievementStartedObjective } from "./types/game/achievement/AchievementStartedObjective";
import { FightDispellableEffectExtendedInformations } from "./types/game/action/fight/FightDispellableEffectExtendedInformations";
import { AbstractFightDispellableEffect } from "./types/game/actions/fight/AbstractFightDispellableEffect";
import { FightDetailedTemporaryBoostEffect } from "./types/game/actions/fight/FightDetailedTemporaryBoostEffect";
import { FightTemporaryBoostEffect } from "./types/game/actions/fight/FightTemporaryBoostEffect";
import { FightTemporaryBoostStateEffect } from "./types/game/actions/fight/FightTemporaryBoostStateEffect";
import { FightTemporaryBoostWeaponDamagesEffect } from "./types/game/actions/fight/FightTemporaryBoostWeaponDamagesEffect";
import { FightTemporarySpellBoostEffect } from "./types/game/actions/fight/FightTemporarySpellBoostEffect";
import { FightTemporarySpellImmunityEffect } from "./types/game/actions/fight/FightTemporarySpellImmunityEffect";
import { FightTriggeredEffect } from "./types/game/actions/fight/FightTriggeredEffect";
import { GameActionMark } from "./types/game/actions/fight/GameActionMark";
import { GameActionMarkedCell } from "./types/game/actions/fight/GameActionMarkedCell";
import { AllianceMemberInfo } from "./types/game/alliance/AllianceMemberInfo";
import { KohAllianceInfo } from "./types/game/alliance/KohAllianceInfo";
import { KohAllianceRoleMembers } from "./types/game/alliance/KohAllianceRoleMembers";
import { KohScore } from "./types/game/alliance/KohScore";
import { KothWinner } from "./types/game/alliance/KothWinner";
import { AllianceRecruitmentInformation } from "./types/game/alliance/recruitment/AllianceRecruitmentInformation";
import { ServerSessionConstant } from "./types/game/approach/ServerSessionConstant";
import { ServerSessionConstantInteger } from "./types/game/approach/ServerSessionConstantInteger";
import { ServerSessionConstantLong } from "./types/game/approach/ServerSessionConstantLong";
import { ServerSessionConstantString } from "./types/game/approach/ServerSessionConstantString";
import { AbstractCharacterInformation } from "./types/game/character/AbstractCharacterInformation";
import { ActorAlignmentInformations } from "./types/game/character/alignment/ActorAlignmentInformations";
import { ActorExtendedAlignmentInformations } from "./types/game/character/alignment/ActorExtendedAlignmentInformations";
import { AlterationInfo } from "./types/game/character/alteration/AlterationInfo";
import { CharacterBasicMinimalInformations } from "./types/game/character/CharacterBasicMinimalInformations";
import { CharacterCharacteristic } from "./types/game/character/characteristic/CharacterCharacteristic";
import { CharacterCharacteristicDetailed } from "./types/game/character/characteristic/CharacterCharacteristicDetailed";
import { CharacterCharacteristics } from "./types/game/character/characteristic/CharacterCharacteristics";
import { CharacterCharacteristicsInformations } from "./types/game/character/characteristic/CharacterCharacteristicsInformations";
import { CharacterCharacteristicValue } from "./types/game/character/characteristic/CharacterCharacteristicValue";
import { CharacterUsableCharacteristicDetailed } from "./types/game/character/characteristic/CharacterUsableCharacteristicDetailed";
import { CharacterMinimalAllianceInformations } from "./types/game/character/CharacterMinimalAllianceInformations";
import { CharacterMinimalGuildInformations } from "./types/game/character/CharacterMinimalGuildInformations";
import { CharacterMinimalInformations } from "./types/game/character/CharacterMinimalInformations";
import { CharacterMinimalPlusLookInformations } from "./types/game/character/CharacterMinimalPlusLookInformations";
import { CharacterMinimalSocialPublicInformations } from "./types/game/character/CharacterMinimalSocialPublicInformations";
import { CharacterBaseInformations } from "./types/game/character/choice/CharacterBaseInformations";
import { CharacterHardcoreOrEpicInformations } from "./types/game/character/choice/CharacterHardcoreOrEpicInformations";
import { CharacterRemodelingInformation } from "./types/game/character/choice/CharacterRemodelingInformation";
import { CharacterToRemodelInformations } from "./types/game/character/choice/CharacterToRemodelInformations";
import { RemodelingInformation } from "./types/game/character/choice/RemodelingInformation";
import { DebtInformation } from "./types/game/character/debt/DebtInformation";
import { KamaDebtInformation } from "./types/game/character/debt/KamaDebtInformation";
import { PlayerNote } from "./types/game/character/guild/note/PlayerNote";
import { ActorRestrictionsInformations } from "./types/game/character/restriction/ActorRestrictionsInformations";
import { SpellModifierMessage } from "./types/game/character/spellmodifier/SpellModifierMessage";
import { PlayerStatus } from "./types/game/character/status/PlayerStatus";
import { PlayerStatusExtended } from "./types/game/character/status/PlayerStatusExtended";
import { AdditionalTaxCollectorInformation } from "./types/game/collector/tax/AdditionalTaxCollectorInformation";
import { TaxCollectorBasicInformations } from "./types/game/collector/tax/TaxCollectorBasicInformations";
import { TaxCollectorComplementaryInformations } from "./types/game/collector/tax/TaxCollectorComplementaryInformations";
import { TaxCollectorInformations } from "./types/game/collector/tax/TaxCollectorInformations";
import { TaxCollectorLootInformations } from "./types/game/collector/tax/TaxCollectorLootInformations";
import { TaxCollectorMovement } from "./types/game/collector/tax/TaxCollectorMovement";
import { TaxCollectorOrderedSpell } from "./types/game/collector/tax/TaxCollectorOrderedSpell";
import { TaxCollectorPreset } from "./types/game/collector/tax/TaxCollectorPreset";
import { TaxCollectorWaitingForHelpInformations } from "./types/game/collector/tax/TaxCollectorWaitingForHelpInformations";
import { ActorOrientation } from "./types/game/context/ActorOrientation";
import { EntityDispositionInformations } from "./types/game/context/EntityDispositionInformations";
import { EntityMovementInformations } from "./types/game/context/EntityMovementInformations";
import { AbstractFightTeamInformations } from "./types/game/context/fight/AbstractFightTeamInformations";
import { BaseSpawnMonsterInformation } from "./types/game/context/fight/BaseSpawnMonsterInformation";
import { ChallengeInformation } from "./types/game/context/fight/challenge/ChallengeInformation";
import { ChallengeTargetInformation } from "./types/game/context/fight/challenge/ChallengeTargetInformation";
import { ChallengeTargetWithAttackerInformation } from "./types/game/context/fight/challenge/ChallengeTargetWithAttackerInformation";
import { FightAllianceTeamInformations } from "./types/game/context/fight/FightAllianceTeamInformations";
import { FightCommonInformations } from "./types/game/context/fight/FightCommonInformations";
import { FightExternalInformations } from "./types/game/context/fight/FightExternalInformations";
import { FightLoot } from "./types/game/context/fight/FightLoot";
import { FightLootObject } from "./types/game/context/fight/FightLootObject";
import { FightOptionsInformations } from "./types/game/context/fight/FightOptionsInformations";
import { FightPhase } from "./types/game/context/fight/FightPhase";
import { FightResultAdditionalData } from "./types/game/context/fight/FightResultAdditionalData";
import { FightResultExperienceData } from "./types/game/context/fight/FightResultExperienceData";
import { FightResultFighterListEntry } from "./types/game/context/fight/FightResultFighterListEntry";
import { FightResultListEntry } from "./types/game/context/fight/FightResultListEntry";
import { FightResultMutantListEntry } from "./types/game/context/fight/FightResultMutantListEntry";
import { FightResultPlayerListEntry } from "./types/game/context/fight/FightResultPlayerListEntry";
import { FightResultPvpData } from "./types/game/context/fight/FightResultPvpData";
import { FightResultTaxCollectorListEntry } from "./types/game/context/fight/FightResultTaxCollectorListEntry";
import { FightStartingPositions } from "./types/game/context/fight/FightStartingPositions";
import { FightTeamInformations } from "./types/game/context/fight/FightTeamInformations";
import { FightTeamLightInformations } from "./types/game/context/fight/FightTeamLightInformations";
import { FightTeamMemberCharacterInformations } from "./types/game/context/fight/FightTeamMemberCharacterInformations";
import { FightTeamMemberEntityInformation } from "./types/game/context/fight/FightTeamMemberEntityInformation";
import { FightTeamMemberInformations } from "./types/game/context/fight/FightTeamMemberInformations";
import { FightTeamMemberMonsterInformations } from "./types/game/context/fight/FightTeamMemberMonsterInformations";
import { FightTeamMemberTaxCollectorInformations } from "./types/game/context/fight/FightTeamMemberTaxCollectorInformations";
import { FightTeamMemberWithAllianceCharacterInformations } from "./types/game/context/fight/FightTeamMemberWithAllianceCharacterInformations";
import { GameContextBasicSpawnInformation } from "./types/game/context/fight/GameContextBasicSpawnInformation";
import { GameContextSummonsInformation } from "./types/game/context/fight/GameContextSummonsInformation";
import { GameFightAIInformations } from "./types/game/context/fight/GameFightAIInformations";
import { GameFightCharacterInformations } from "./types/game/context/fight/GameFightCharacterInformations";
import { GameFightCharacteristics } from "./types/game/context/fight/GameFightCharacteristics";
import { GameFightEffectTriggerCount } from "./types/game/context/fight/GameFightEffectTriggerCount";
import { GameFightEntityInformation } from "./types/game/context/fight/GameFightEntityInformation";
import { GameFightFighterEntityLightInformation } from "./types/game/context/fight/GameFightFighterEntityLightInformation";
import { GameFightFighterInformations } from "./types/game/context/fight/GameFightFighterInformations";
import { GameFightFighterLightInformations } from "./types/game/context/fight/GameFightFighterLightInformations";
import { GameFightFighterMonsterLightInformations } from "./types/game/context/fight/GameFightFighterMonsterLightInformations";
import { GameFightFighterNamedInformations } from "./types/game/context/fight/GameFightFighterNamedInformations";
import { GameFightFighterNamedLightInformations } from "./types/game/context/fight/GameFightFighterNamedLightInformations";
import { GameFightFighterTaxCollectorLightInformations } from "./types/game/context/fight/GameFightFighterTaxCollectorLightInformations";
import { GameFightMonsterInformations } from "./types/game/context/fight/GameFightMonsterInformations";
import { GameFightMonsterWithAlignmentInformations } from "./types/game/context/fight/GameFightMonsterWithAlignmentInformations";
import { GameFightMutantInformations } from "./types/game/context/fight/GameFightMutantInformations";
import { GameFightResumeSlaveInfo } from "./types/game/context/fight/GameFightResumeSlaveInfo";
import { GameFightSpellCooldown } from "./types/game/context/fight/GameFightSpellCooldown";
import { GameFightTaxCollectorInformations } from "./types/game/context/fight/GameFightTaxCollectorInformations";
import { SpawnCharacterInformation } from "./types/game/context/fight/SpawnCharacterInformation";
import { SpawnCompanionInformation } from "./types/game/context/fight/SpawnCompanionInformation";
import { SpawnInformation } from "./types/game/context/fight/SpawnInformation";
import { SpawnMonsterInformation } from "./types/game/context/fight/SpawnMonsterInformation";
import { SpawnScaledMonsterInformation } from "./types/game/context/fight/SpawnScaledMonsterInformation";
import { FightEntityDispositionInformations } from "./types/game/context/FightEntityDispositionInformations";
import { GameContextActorInformations } from "./types/game/context/GameContextActorInformations";
import { GameContextActorPositionInformations } from "./types/game/context/GameContextActorPositionInformations";
import { GameRolePlayTaxCollectorInformations } from "./types/game/context/GameRolePlayTaxCollectorInformations";
import { IdentifiedEntityDispositionInformations } from "./types/game/context/IdentifiedEntityDispositionInformations";
import { MapCoordinates } from "./types/game/context/MapCoordinates";
import { MapCoordinatesAndId } from "./types/game/context/MapCoordinatesAndId";
import { MapCoordinatesExtended } from "./types/game/context/MapCoordinatesExtended";
import { AlignmentWarEffortInformation } from "./types/game/context/roleplay/alignment/war/effort/AlignmentWarEffortInformation";
import { AllianceInformation } from "./types/game/context/roleplay/AllianceInformation";
import { AlternativeMonstersInGroupLightInformations } from "./types/game/context/roleplay/AlternativeMonstersInGroupLightInformations";
import { AnomalySubareaInformation } from "./types/game/context/roleplay/AnomalySubareaInformation";
import { AtlasPointsInformations } from "./types/game/context/roleplay/AtlasPointsInformations";
import { BasicAllianceInformations } from "./types/game/context/roleplay/BasicAllianceInformations";
import { BasicGuildInformations } from "./types/game/context/roleplay/BasicGuildInformations";
import { BasicNamedAllianceInformations } from "./types/game/context/roleplay/BasicNamedAllianceInformations";
import { BreachBranch } from "./types/game/context/roleplay/breach/BreachBranch";
import { BreachReward } from "./types/game/context/roleplay/breach/BreachReward";
import { ExtendedBreachBranch } from "./types/game/context/roleplay/breach/ExtendedBreachBranch";
import { ExtendedLockedBreachBranch } from "./types/game/context/roleplay/breach/ExtendedLockedBreachBranch";
import { ArenaLeagueRanking } from "./types/game/context/roleplay/fight/arena/ArenaLeagueRanking";
import { ArenaRankInfos } from "./types/game/context/roleplay/fight/arena/ArenaRankInfos";
import { LeagueFriendInformations } from "./types/game/context/roleplay/fight/arena/LeagueFriendInformations";
import { GameRolePlayActorInformations } from "./types/game/context/roleplay/GameRolePlayActorInformations";
import { GameRolePlayCharacterInformations } from "./types/game/context/roleplay/GameRolePlayCharacterInformations";
import { GameRolePlayGroupMonsterInformations } from "./types/game/context/roleplay/GameRolePlayGroupMonsterInformations";
import { GameRolePlayGroupMonsterWaveInformations } from "./types/game/context/roleplay/GameRolePlayGroupMonsterWaveInformations";
import { GameRolePlayHumanoidInformations } from "./types/game/context/roleplay/GameRolePlayHumanoidInformations";
import { GameRolePlayMountInformations } from "./types/game/context/roleplay/GameRolePlayMountInformations";
import { GameRolePlayMutantInformations } from "./types/game/context/roleplay/GameRolePlayMutantInformations";
import { GameRolePlayNamedActorInformations } from "./types/game/context/roleplay/GameRolePlayNamedActorInformations";
import { GameRolePlayNpcInformations } from "./types/game/context/roleplay/GameRolePlayNpcInformations";
import { GameRolePlayNpcWithQuestInformations } from "./types/game/context/roleplay/GameRolePlayNpcWithQuestInformations";
import { GameRolePlayPortalInformations } from "./types/game/context/roleplay/GameRolePlayPortalInformations";
import { GameRolePlayPrismInformations } from "./types/game/context/roleplay/GameRolePlayPrismInformations";
import { GameRolePlayTreasureHintInformations } from "./types/game/context/roleplay/GameRolePlayTreasureHintInformations";
import { GroupMonsterStaticInformations } from "./types/game/context/roleplay/GroupMonsterStaticInformations";
import { GroupMonsterStaticInformationsWithAlternatives } from "./types/game/context/roleplay/GroupMonsterStaticInformationsWithAlternatives";
import { GuildInformations } from "./types/game/context/roleplay/GuildInformations";
import { HumanInformations } from "./types/game/context/roleplay/HumanInformations";
import { HumanOption } from "./types/game/context/roleplay/HumanOption";
import { HumanOptionAlliance } from "./types/game/context/roleplay/HumanOptionAlliance";
import { HumanOptionEmote } from "./types/game/context/roleplay/HumanOptionEmote";
import { HumanOptionFollowers } from "./types/game/context/roleplay/HumanOptionFollowers";
import { HumanOptionGuild } from "./types/game/context/roleplay/HumanOptionGuild";
import { HumanOptionObjectUse } from "./types/game/context/roleplay/HumanOptionObjectUse";
import { HumanOptionOrnament } from "./types/game/context/roleplay/HumanOptionOrnament";
import { HumanOptionSkillUse } from "./types/game/context/roleplay/HumanOptionSkillUse";
import { HumanOptionSpeedMultiplier } from "./types/game/context/roleplay/HumanOptionSpeedMultiplier";
import { HumanOptionTitle } from "./types/game/context/roleplay/HumanOptionTitle";
import { DecraftedItemStackInfo } from "./types/game/context/roleplay/job/DecraftedItemStackInfo";
import { JobBookSubscription } from "./types/game/context/roleplay/job/JobBookSubscription";
import { JobCrafterDirectoryEntryJobInfo } from "./types/game/context/roleplay/job/JobCrafterDirectoryEntryJobInfo";
import { JobCrafterDirectoryEntryPlayerInfo } from "./types/game/context/roleplay/job/JobCrafterDirectoryEntryPlayerInfo";
import { JobCrafterDirectoryListEntry } from "./types/game/context/roleplay/job/JobCrafterDirectoryListEntry";
import { JobCrafterDirectorySettings } from "./types/game/context/roleplay/job/JobCrafterDirectorySettings";
import { JobDescription } from "./types/game/context/roleplay/job/JobDescription";
import { JobExperience } from "./types/game/context/roleplay/job/JobExperience";
import { MonsterBoosts } from "./types/game/context/roleplay/MonsterBoosts";
import { MonsterInGroupInformations } from "./types/game/context/roleplay/MonsterInGroupInformations";
import { MonsterInGroupLightInformations } from "./types/game/context/roleplay/MonsterInGroupLightInformations";
import { MapNpcQuestInfo } from "./types/game/context/roleplay/npc/MapNpcQuestInfo";
import { ObjectItemInRolePlay } from "./types/game/context/roleplay/ObjectItemInRolePlay";
import { DungeonPartyFinderPlayer } from "./types/game/context/roleplay/party/DungeonPartyFinderPlayer";
import { PartyEntityBaseInformation } from "./types/game/context/roleplay/party/entity/PartyEntityBaseInformation";
import { PartyEntityMemberInformation } from "./types/game/context/roleplay/party/entity/PartyEntityMemberInformation";
import { NamedPartyTeam } from "./types/game/context/roleplay/party/NamedPartyTeam";
import { NamedPartyTeamWithOutcome } from "./types/game/context/roleplay/party/NamedPartyTeamWithOutcome";
import { PartyGuestInformations } from "./types/game/context/roleplay/party/PartyGuestInformations";
import { PartyInvitationMemberInformations } from "./types/game/context/roleplay/party/PartyInvitationMemberInformations";
import { PartyMemberArenaInformations } from "./types/game/context/roleplay/party/PartyMemberArenaInformations";
import { PartyMemberGeoPosition } from "./types/game/context/roleplay/party/PartyMemberGeoPosition";
import { PartyMemberInformations } from "./types/game/context/roleplay/party/PartyMemberInformations";
import { GameRolePlayNpcQuestFlag } from "./types/game/context/roleplay/quest/GameRolePlayNpcQuestFlag";
import { QuestActiveDetailedInformations } from "./types/game/context/roleplay/quest/QuestActiveDetailedInformations";
import { QuestActiveInformations } from "./types/game/context/roleplay/quest/QuestActiveInformations";
import { QuestObjectiveInformations } from "./types/game/context/roleplay/quest/QuestObjectiveInformations";
import { QuestObjectiveInformationsWithCompletion } from "./types/game/context/roleplay/quest/QuestObjectiveInformationsWithCompletion";
import { PortalInformation } from "./types/game/context/roleplay/treasureHunt/PortalInformation";
import { TreasureHuntFlag } from "./types/game/context/roleplay/treasureHunt/TreasureHuntFlag";
import { TreasureHuntStep } from "./types/game/context/roleplay/treasureHunt/TreasureHuntStep";
import { TreasureHuntStepDig } from "./types/game/context/roleplay/treasureHunt/TreasureHuntStepDig";
import { TreasureHuntStepFight } from "./types/game/context/roleplay/treasureHunt/TreasureHuntStepFight";
import { TreasureHuntStepFollowDirection } from "./types/game/context/roleplay/treasureHunt/TreasureHuntStepFollowDirection";
import { TreasureHuntStepFollowDirectionToHint } from "./types/game/context/roleplay/treasureHunt/TreasureHuntStepFollowDirectionToHint";
import { TreasureHuntStepFollowDirectionToPOI } from "./types/game/context/roleplay/treasureHunt/TreasureHuntStepFollowDirectionToPOI";
import { TaxCollectorStaticInformations } from "./types/game/context/TaxCollectorStaticInformations";
import { BidExchangerObjectInfo } from "./types/game/data/items/BidExchangerObjectInfo";
import { ObjectEffect } from "./types/game/data/items/effects/ObjectEffect";
import { ObjectEffectCreature } from "./types/game/data/items/effects/ObjectEffectCreature";
import { ObjectEffectDate } from "./types/game/data/items/effects/ObjectEffectDate";
import { ObjectEffectDice } from "./types/game/data/items/effects/ObjectEffectDice";
import { ObjectEffectDuration } from "./types/game/data/items/effects/ObjectEffectDuration";
import { ObjectEffectInteger } from "./types/game/data/items/effects/ObjectEffectInteger";
import { ObjectEffectLadder } from "./types/game/data/items/effects/ObjectEffectLadder";
import { ObjectEffectMinMax } from "./types/game/data/items/effects/ObjectEffectMinMax";
import { ObjectEffectMount } from "./types/game/data/items/effects/ObjectEffectMount";
import { ObjectEffectString } from "./types/game/data/items/effects/ObjectEffectString";
import { ForgettableSpellItem } from "./types/game/data/items/ForgettableSpellItem";
import { GoldItem } from "./types/game/data/items/GoldItem";
import { Item } from "./types/game/data/items/Item";
import { ObjectEffects } from "./types/game/data/items/ObjectEffects";
import { ObjectItem } from "./types/game/data/items/ObjectItem";
import { ObjectItemGenericQuantity } from "./types/game/data/items/ObjectItemGenericQuantity";
import { ObjectItemInformationWithQuantity } from "./types/game/data/items/ObjectItemInformationWithQuantity";
import { ObjectItemMinimalInformation } from "./types/game/data/items/ObjectItemMinimalInformation";
import { ObjectItemNotInContainer } from "./types/game/data/items/ObjectItemNotInContainer";
import { ObjectItemQuantity } from "./types/game/data/items/ObjectItemQuantity";
import { ObjectItemQuantityPriceDateEffects } from "./types/game/data/items/ObjectItemQuantityPriceDateEffects";
import { ObjectItemToSell } from "./types/game/data/items/ObjectItemToSell";
import { ObjectItemToSellInBid } from "./types/game/data/items/ObjectItemToSellInBid";
import { ObjectItemToSellInNpcShop } from "./types/game/data/items/ObjectItemToSellInNpcShop";
import { SellerBuyerDescriptor } from "./types/game/data/items/SellerBuyerDescriptor";
import { SpellItem } from "./types/game/data/items/SpellItem";
import { EntityInformation } from "./types/game/entity/EntityInformation";
import { ProtectedEntityWaitingForHelpInfo } from "./types/game/fight/ProtectedEntityWaitingForHelpInfo";
import { FinishMoveInformations } from "./types/game/finishmoves/FinishMoveInformations";
import { AbstractContactInformations } from "./types/game/friend/AbstractContactInformations";
import { AcquaintanceInformation } from "./types/game/friend/AcquaintanceInformation";
import { AcquaintanceOnlineInformation } from "./types/game/friend/AcquaintanceOnlineInformation";
import { FriendInformations } from "./types/game/friend/FriendInformations";
import { FriendOnlineInformations } from "./types/game/friend/FriendOnlineInformations";
import { FriendSpouseInformations } from "./types/game/friend/FriendSpouseInformations";
import { FriendSpouseOnlineInformations } from "./types/game/friend/FriendSpouseOnlineInformations";
import { IgnoredInformations } from "./types/game/friend/IgnoredInformations";
import { IgnoredOnlineInformations } from "./types/game/friend/IgnoredOnlineInformations";
import { Contribution } from "./types/game/guild/Contribution";
import { GuildMemberInfo } from "./types/game/guild/GuildMemberInfo";
import { HavenBagFurnitureInformation } from "./types/game/guild/HavenBagFurnitureInformation";
import { GuildLogbookChestActivity } from "./types/game/guild/logbook/chest/GuildLogbookChestActivity";
import { GuildLevelUpActivity } from "./types/game/guild/logbook/global/GuildLevelUpActivity";
import { GuildPaddockActivity } from "./types/game/guild/logbook/global/GuildPaddockActivity";
import { GuildPlayerFlowActivity } from "./types/game/guild/logbook/global/GuildPlayerFlowActivity";
import { GuildPlayerRankUpdateActivity } from "./types/game/guild/logbook/global/GuildPlayerRankUpdateActivity";
import { GuildRankActivity } from "./types/game/guild/logbook/global/GuildRankActivity";
import { GuildUnlockNewTabActivity } from "./types/game/guild/logbook/global/GuildUnlockNewTabActivity";
import { GuildLogbookEntryBasicInformation } from "./types/game/guild/logbook/GuildLogbookEntryBasicInformation";
import { RankPublicInformation } from "./types/game/guild/RankPublicInformation";
import { GuildRecruitmentInformation } from "./types/game/guild/recruitment/GuildRecruitmentInformation";
import { HavenBagRoomPreviewInformation } from "./types/game/havenbag/HavenBagRoomPreviewInformation";
import { AccountHouseInformations } from "./types/game/house/AccountHouseInformations";
import { HouseGuildedInformations } from "./types/game/house/HouseGuildedInformations";
import { HouseInformations } from "./types/game/house/HouseInformations";
import { HouseInformationsForGuild } from "./types/game/house/HouseInformationsForGuild";
import { HouseInformationsForSell } from "./types/game/house/HouseInformationsForSell";
import { HouseInformationsInside } from "./types/game/house/HouseInformationsInside";
import { HouseInstanceInformations } from "./types/game/house/HouseInstanceInformations";
import { HouseOnMapInformations } from "./types/game/house/HouseOnMapInformations";
import { InteractiveElement } from "./types/game/interactive/InteractiveElement";
import { InteractiveElementNamedSkill } from "./types/game/interactive/InteractiveElementNamedSkill";
import { InteractiveElementSkill } from "./types/game/interactive/InteractiveElementSkill";
import { InteractiveElementWithAgeBonus } from "./types/game/interactive/InteractiveElementWithAgeBonus";
import { MapObstacle } from "./types/game/interactive/MapObstacle";
import { SkillActionDescription } from "./types/game/interactive/skill/SkillActionDescription";
import { SkillActionDescriptionCollect } from "./types/game/interactive/skill/SkillActionDescriptionCollect";
import { SkillActionDescriptionCraft } from "./types/game/interactive/skill/SkillActionDescriptionCraft";
import { SkillActionDescriptionTimed } from "./types/game/interactive/skill/SkillActionDescriptionTimed";
import { StatedElement } from "./types/game/interactive/StatedElement";
import { TeleportDestination } from "./types/game/interactive/zaap/TeleportDestination";
import { RecycledItem } from "./types/game/inventory/exchanges/RecycledItem";
import { StorageTabInformation } from "./types/game/inventory/StorageTabInformation";
import { UpdatedStorageTabInformation } from "./types/game/inventory/UpdatedStorageTabInformation";
import { EntityLook } from "./types/game/look/EntityLook";
import { IndexedEntityLook } from "./types/game/look/IndexedEntityLook";
import { SubEntity } from "./types/game/look/SubEntity";
import { ItemDurability } from "./types/game/mount/ItemDurability";
import { MountClientData } from "./types/game/mount/MountClientData";
import { UpdateMountBooleanCharacteristic } from "./types/game/mount/UpdateMountBooleanCharacteristic";
import { UpdateMountCharacteristic } from "./types/game/mount/UpdateMountCharacteristic";
import { UpdateMountIntegerCharacteristic } from "./types/game/mount/UpdateMountIntegerCharacteristic";
import { NuggetsBeneficiary } from "./types/game/nuggets/NuggetsBeneficiary";
import { MountInformationsForPaddock } from "./types/game/paddock/MountInformationsForPaddock";
import { PaddockBuyableInformations } from "./types/game/paddock/PaddockBuyableInformations";
import { PaddockContentInformations } from "./types/game/paddock/PaddockContentInformations";
import { PaddockGuildedInformations } from "./types/game/paddock/PaddockGuildedInformations";
import { PaddockInformations } from "./types/game/paddock/PaddockInformations";
import { PaddockInformationsForSell } from "./types/game/paddock/PaddockInformationsForSell";
import { PaddockInstancesInformations } from "./types/game/paddock/PaddockInstancesInformations";
import { PaddockItem } from "./types/game/paddock/PaddockItem";
import { CharacterCharacteristicForPreset } from "./types/game/presets/CharacterCharacteristicForPreset";
import { EntitiesPreset } from "./types/game/presets/EntitiesPreset";
import { ForgettableSpellsPreset } from "./types/game/presets/ForgettableSpellsPreset";
import { FullStatsPreset } from "./types/game/presets/FullStatsPreset";
import { IconNamedPreset } from "./types/game/presets/IconNamedPreset";
import { ItemForPreset } from "./types/game/presets/ItemForPreset";
import { ItemsPreset } from "./types/game/presets/ItemsPreset";
import { Preset } from "./types/game/presets/Preset";
import { PresetsContainerPreset } from "./types/game/presets/PresetsContainerPreset";
import { SimpleCharacterCharacteristicForPreset } from "./types/game/presets/SimpleCharacterCharacteristicForPreset";
import { SpellForPreset } from "./types/game/presets/SpellForPreset";
import { SpellsPreset } from "./types/game/presets/SpellsPreset";
import { StatsPreset } from "./types/game/presets/StatsPreset";
import { AllianceInsiderPrismInformation } from "./types/game/prism/AllianceInsiderPrismInformation";
import { AlliancePrismInformation } from "./types/game/prism/AlliancePrismInformation";
import { PrismGeolocalizedInformation } from "./types/game/prism/PrismGeolocalizedInformation";
import { PrismInformation } from "./types/game/prism/PrismInformation";
import { AgressableStatusMessage } from "./types/game/pvp/AgressableStatusMessage";
import { RankInformation } from "./types/game/rank/RankInformation";
import { RankMinimalInformation } from "./types/game/rank/RankMinimalInformation";
import { Shortcut } from "./types/game/shortcut/Shortcut";
import { ShortcutEmote } from "./types/game/shortcut/ShortcutEmote";
import { ShortcutEntitiesPreset } from "./types/game/shortcut/ShortcutEntitiesPreset";
import { ShortcutObject } from "./types/game/shortcut/ShortcutObject";
import { ShortcutObjectItem } from "./types/game/shortcut/ShortcutObjectItem";
import { ShortcutObjectPreset } from "./types/game/shortcut/ShortcutObjectPreset";
import { ShortcutSmiley } from "./types/game/shortcut/ShortcutSmiley";
import { ShortcutSpell } from "./types/game/shortcut/ShortcutSpell";
import { AbstractSocialGroupInfos } from "./types/game/social/AbstractSocialGroupInfos";
import { AllianceFactSheetInformation } from "./types/game/social/AllianceFactSheetInformation";
import { ApplicationPlayerInformation } from "./types/game/social/application/ApplicationPlayerInformation";
import { SocialApplicationInformation } from "./types/game/social/application/SocialApplicationInformation";
import { SocialFight } from "./types/game/social/fight/SocialFight";
import { SocialFightInfo } from "./types/game/social/fight/SocialFightInfo";
import { GuildFactSheetInformations } from "./types/game/social/GuildFactSheetInformations";
import { GuildInsiderFactSheetInformations } from "./types/game/social/GuildInsiderFactSheetInformations";
import { SocialRecruitmentInformation } from "./types/game/social/recruitment/SocialRecruitmentInformation";
import { SocialEmblem } from "./types/game/social/SocialEmblem";
import { SocialMember } from "./types/game/social/SocialMember";
import { GameActionItem } from "./types/game/startup/GameActionItem";
import { SurrenderAccepted } from "./types/game/surrender/SurrenderAccepted";
import { SurrenderRefused } from "./types/game/surrender/SurrenderRefused";
import { SurrenderRefusedBeforeTurn } from "./types/game/surrender/SurrenderRefusedBeforeTurn";
import { SurrenderRefusedBeforeVote } from "./types/game/surrender/SurrenderRefusedBeforeVote";
import { SurrenderResponse } from "./types/game/surrender/SurrenderResponse";
import { SurrenderVoteAccepted } from "./types/game/surrender/vote/SurrenderVoteAccepted";
import { SurrenderVoteRefused } from "./types/game/surrender/vote/SurrenderVoteRefused";
import { SurrenderVoteRefusedAlreadyAsked } from "./types/game/surrender/vote/SurrenderVoteRefusedAlreadyAsked";
import { SurrenderVoteRefusedBeforeTurn } from "./types/game/surrender/vote/SurrenderVoteRefusedBeforeTurn";
import { SurrenderVoteRefusedWaitBetweenVotes } from "./types/game/surrender/vote/SurrenderVoteRefusedWaitBetweenVotes";
import { SurrenderVoteResponse } from "./types/game/surrender/vote/SurrenderVoteResponse";
import { Uuid } from "./types/game/Uuid";
import { TrustCertificate } from "./types/secure/TrustCertificate";
import { Version } from "./types/version/Version";
import { BufferInformation } from "./types/web/haapi/BufferInformation";


export class ProtocolTypeManager {

	private static readonly _types: Array<{ new(): any }> = Array<{ new(): any }>();
	
	static {
				this._types[1300] = AbstractPlayerSearchInformation;
		this._types[3196] = AccountTagInformation;
		this._types[1815] = StatisticData;
		this._types[7901] = StatisticDataBoolean;
		this._types[4573] = StatisticDataByte;
		this._types[7834] = StatisticDataInt;
		this._types[1762] = StatisticDataShort;
		this._types[4102] = StatisticDataString;
		this._types[3022] = PlayerSearchCharacterNameInformation;
		this._types[3389] = PlayerSearchTagInformation;
		this._types[4792] = GameServerInformations;
		this._types[2764] = Achievement;
		this._types[6607] = AchievementAchieved;
		this._types[9874] = AchievementAchievedRewardable;
		this._types[2341] = AchievementObjective;
		this._types[6487] = AchievementPioneerRank;
		this._types[5360] = AchievementStartedObjective;
		this._types[8836] = FightDispellableEffectExtendedInformations;
		this._types[4079] = AbstractFightDispellableEffect;
		this._types[2061] = FightDetailedTemporaryBoostEffect;
		this._types[2521] = FightTemporaryBoostEffect;
		this._types[4574] = FightTemporaryBoostStateEffect;
		this._types[9695] = FightTemporaryBoostWeaponDamagesEffect;
		this._types[7119] = FightTemporarySpellBoostEffect;
		this._types[3450] = FightTemporarySpellImmunityEffect;
		this._types[5487] = FightTriggeredEffect;
		this._types[8022] = GameActionMark;
		this._types[5710] = GameActionMarkedCell;
		this._types[7753] = AllianceMemberInfo;
		this._types[7195] = KohAllianceInfo;
		this._types[9987] = KohAllianceRoleMembers;
		this._types[5560] = KohScore;
		this._types[4121] = KothWinner;
		this._types[4753] = AllianceRecruitmentInformation;
		this._types[9977] = ServerSessionConstant;
		this._types[2867] = ServerSessionConstantInteger;
		this._types[4175] = ServerSessionConstantLong;
		this._types[7359] = ServerSessionConstantString;
		this._types[5789] = AbstractCharacterInformation;
		this._types[2626] = ActorAlignmentInformations;
		this._types[4048] = ActorExtendedAlignmentInformations;
		this._types[2959] = AlterationInfo;
		this._types[6994] = CharacterBasicMinimalInformations;
		this._types[6701] = CharacterCharacteristic;
		this._types[901] = CharacterCharacteristicDetailed;
		this._types[294] = CharacterCharacteristics;
		this._types[4504] = CharacterCharacteristicsInformations;
		this._types[3951] = CharacterCharacteristicValue;
		this._types[1943] = CharacterUsableCharacteristicDetailed;
		this._types[4814] = CharacterMinimalAllianceInformations;
		this._types[2143] = CharacterMinimalGuildInformations;
		this._types[9474] = CharacterMinimalInformations;
		this._types[1529] = CharacterMinimalPlusLookInformations;
		this._types[5126] = CharacterMinimalSocialPublicInformations;
		this._types[4367] = CharacterBaseInformations;
		this._types[3983] = CharacterHardcoreOrEpicInformations;
		this._types[5105] = CharacterRemodelingInformation;
		this._types[3313] = CharacterToRemodelInformations;
		this._types[3743] = RemodelingInformation;
		this._types[8943] = DebtInformation;
		this._types[2104] = KamaDebtInformation;
		this._types[3703] = PlayerNote;
		this._types[9953] = ActorRestrictionsInformations;
		this._types[2892] = SpellModifierMessage;
		this._types[2273] = PlayerStatus;
		this._types[8257] = PlayerStatusExtended;
		this._types[1456] = AdditionalTaxCollectorInformation;
		this._types[4890] = TaxCollectorBasicInformations;
		this._types[1982] = TaxCollectorComplementaryInformations;
		this._types[4158] = TaxCollectorInformations;
		this._types[4183] = TaxCollectorLootInformations;
		this._types[7487] = TaxCollectorMovement;
		this._types[3173] = TaxCollectorOrderedSpell;
		this._types[1854] = TaxCollectorPreset;
		this._types[5931] = TaxCollectorWaitingForHelpInformations;
		this._types[2066] = ActorOrientation;
		this._types[2447] = EntityDispositionInformations;
		this._types[4990] = EntityMovementInformations;
		this._types[8432] = AbstractFightTeamInformations;
		this._types[5062] = BaseSpawnMonsterInformation;
		this._types[1494] = ChallengeInformation;
		this._types[4052] = ChallengeTargetInformation;
		this._types[540] = ChallengeTargetWithAttackerInformation;
		this._types[8585] = FightAllianceTeamInformations;
		this._types[9113] = FightCommonInformations;
		this._types[3630] = FightExternalInformations;
		this._types[3066] = FightLoot;
		this._types[5840] = FightLootObject;
		this._types[1574] = FightOptionsInformations;
		this._types[2770] = FightPhase;
		this._types[8078] = FightResultAdditionalData;
		this._types[5571] = FightResultExperienceData;
		this._types[613] = FightResultFighterListEntry;
		this._types[3594] = FightResultListEntry;
		this._types[2795] = FightResultMutantListEntry;
		this._types[6813] = FightResultPlayerListEntry;
		this._types[7233] = FightResultPvpData;
		this._types[6507] = FightResultTaxCollectorListEntry;
		this._types[5557] = FightStartingPositions;
		this._types[3291] = FightTeamInformations;
		this._types[6964] = FightTeamLightInformations;
		this._types[4535] = FightTeamMemberCharacterInformations;
		this._types[5854] = FightTeamMemberEntityInformation;
		this._types[9810] = FightTeamMemberInformations;
		this._types[7397] = FightTeamMemberMonsterInformations;
		this._types[4832] = FightTeamMemberTaxCollectorInformations;
		this._types[793] = FightTeamMemberWithAllianceCharacterInformations;
		this._types[1891] = GameContextBasicSpawnInformation;
		this._types[5419] = GameContextSummonsInformation;
		this._types[8061] = GameFightAIInformations;
		this._types[3578] = GameFightCharacterInformations;
		this._types[714] = GameFightCharacteristics;
		this._types[7405] = GameFightEffectTriggerCount;
		this._types[4556] = GameFightEntityInformation;
		this._types[3181] = GameFightFighterEntityLightInformation;
		this._types[5601] = GameFightFighterInformations;
		this._types[4794] = GameFightFighterLightInformations;
		this._types[3925] = GameFightFighterMonsterLightInformations;
		this._types[4176] = GameFightFighterNamedInformations;
		this._types[5195] = GameFightFighterNamedLightInformations;
		this._types[3310] = GameFightFighterTaxCollectorLightInformations;
		this._types[1792] = GameFightMonsterInformations;
		this._types[7656] = GameFightMonsterWithAlignmentInformations;
		this._types[419] = GameFightMutantInformations;
		this._types[6502] = GameFightResumeSlaveInfo;
		this._types[9361] = GameFightSpellCooldown;
		this._types[7175] = GameFightTaxCollectorInformations;
		this._types[3409] = SpawnCharacterInformation;
		this._types[4847] = SpawnCompanionInformation;
		this._types[339] = SpawnInformation;
		this._types[571] = SpawnMonsterInformation;
		this._types[8568] = SpawnScaledMonsterInformation;
		this._types[3736] = FightEntityDispositionInformations;
		this._types[9060] = GameContextActorInformations;
		this._types[3056] = GameContextActorPositionInformations;
		this._types[4101] = GameRolePlayTaxCollectorInformations;
		this._types[619] = IdentifiedEntityDispositionInformations;
		this._types[315] = MapCoordinates;
		this._types[7010] = MapCoordinatesAndId;
		this._types[1599] = MapCoordinatesExtended;
		this._types[6941] = AlignmentWarEffortInformation;
		this._types[1197] = AllianceInformation;
		this._types[6089] = AlternativeMonstersInGroupLightInformations;
		this._types[4038] = AnomalySubareaInformation;
		this._types[6167] = AtlasPointsInformations;
		this._types[2995] = BasicAllianceInformations;
		this._types[4606] = BasicGuildInformations;
		this._types[5416] = BasicNamedAllianceInformations;
		this._types[7507] = BreachBranch;
		this._types[3273] = BreachReward;
		this._types[8307] = ExtendedBreachBranch;
		this._types[4080] = ExtendedLockedBreachBranch;
		this._types[3976] = ArenaLeagueRanking;
		this._types[2174] = ArenaRankInfos;
		this._types[7750] = LeagueFriendInformations;
		this._types[8764] = GameRolePlayActorInformations;
		this._types[9304] = GameRolePlayCharacterInformations;
		this._types[7360] = GameRolePlayGroupMonsterInformations;
		this._types[6822] = GameRolePlayGroupMonsterWaveInformations;
		this._types[9318] = GameRolePlayHumanoidInformations;
		this._types[9212] = GameRolePlayMountInformations;
		this._types[2574] = GameRolePlayMutantInformations;
		this._types[2808] = GameRolePlayNamedActorInformations;
		this._types[8347] = GameRolePlayNpcInformations;
		this._types[7588] = GameRolePlayNpcWithQuestInformations;
		this._types[9999] = GameRolePlayPortalInformations;
		this._types[7369] = GameRolePlayPrismInformations;
		this._types[9279] = GameRolePlayTreasureHintInformations;
		this._types[5953] = GroupMonsterStaticInformations;
		this._types[4829] = GroupMonsterStaticInformationsWithAlternatives;
		this._types[7929] = GuildInformations;
		this._types[495] = HumanInformations;
		this._types[7701] = HumanOption;
		this._types[7953] = HumanOptionAlliance;
		this._types[7646] = HumanOptionEmote;
		this._types[8287] = HumanOptionFollowers;
		this._types[1132] = HumanOptionGuild;
		this._types[446] = HumanOptionObjectUse;
		this._types[5782] = HumanOptionOrnament;
		this._types[2036] = HumanOptionSkillUse;
		this._types[4364] = HumanOptionSpeedMultiplier;
		this._types[2189] = HumanOptionTitle;
		this._types[2478] = DecraftedItemStackInfo;
		this._types[5496] = JobBookSubscription;
		this._types[5157] = JobCrafterDirectoryEntryJobInfo;
		this._types[9204] = JobCrafterDirectoryEntryPlayerInfo;
		this._types[7693] = JobCrafterDirectoryListEntry;
		this._types[7939] = JobCrafterDirectorySettings;
		this._types[4698] = JobDescription;
		this._types[1492] = JobExperience;
		this._types[1084] = MonsterBoosts;
		this._types[7023] = MonsterInGroupInformations;
		this._types[1537] = MonsterInGroupLightInformations;
		this._types[7887] = MapNpcQuestInfo;
		this._types[1282] = ObjectItemInRolePlay;
		this._types[1061] = DungeonPartyFinderPlayer;
		this._types[5790] = PartyEntityBaseInformation;
		this._types[118] = PartyEntityMemberInformation;
		this._types[9179] = NamedPartyTeam;
		this._types[2171] = NamedPartyTeamWithOutcome;
		this._types[3127] = PartyGuestInformations;
		this._types[3577] = PartyInvitationMemberInformations;
		this._types[2056] = PartyMemberArenaInformations;
		this._types[5313] = PartyMemberGeoPosition;
		this._types[9391] = PartyMemberInformations;
		this._types[6478] = GameRolePlayNpcQuestFlag;
		this._types[7451] = QuestActiveDetailedInformations;
		this._types[7048] = QuestActiveInformations;
		this._types[7248] = QuestObjectiveInformations;
		this._types[8731] = QuestObjectiveInformationsWithCompletion;
		this._types[2396] = PortalInformation;
		this._types[8258] = TreasureHuntFlag;
		this._types[8185] = TreasureHuntStep;
		this._types[5858] = TreasureHuntStepDig;
		this._types[9719] = TreasureHuntStepFight;
		this._types[9008] = TreasureHuntStepFollowDirection;
		this._types[8809] = TreasureHuntStepFollowDirectionToHint;
		this._types[9275] = TreasureHuntStepFollowDirectionToPOI;
		this._types[1672] = TaxCollectorStaticInformations;
		this._types[2811] = BidExchangerObjectInfo;
		this._types[7605] = ObjectEffect;
		this._types[3987] = ObjectEffectCreature;
		this._types[3435] = ObjectEffectDate;
		this._types[670] = ObjectEffectDice;
		this._types[7031] = ObjectEffectDuration;
		this._types[3930] = ObjectEffectInteger;
		this._types[5489] = ObjectEffectLadder;
		this._types[843] = ObjectEffectMinMax;
		this._types[3353] = ObjectEffectMount;
		this._types[3424] = ObjectEffectString;
		this._types[2798] = ForgettableSpellItem;
		this._types[8076] = GoldItem;
		this._types[8235] = Item;
		this._types[6602] = ObjectEffects;
		this._types[1685] = ObjectItem;
		this._types[7294] = ObjectItemGenericQuantity;
		this._types[8098] = ObjectItemInformationWithQuantity;
		this._types[9931] = ObjectItemMinimalInformation;
		this._types[7571] = ObjectItemNotInContainer;
		this._types[5434] = ObjectItemQuantity;
		this._types[3552] = ObjectItemQuantityPriceDateEffects;
		this._types[9372] = ObjectItemToSell;
		this._types[859] = ObjectItemToSellInBid;
		this._types[5301] = ObjectItemToSellInNpcShop;
		this._types[780] = SellerBuyerDescriptor;
		this._types[8615] = SpellItem;
		this._types[9779] = EntityInformation;
		this._types[9739] = ProtectedEntityWaitingForHelpInfo;
		this._types[8829] = FinishMoveInformations;
		this._types[8841] = AbstractContactInformations;
		this._types[1584] = AcquaintanceInformation;
		this._types[251] = AcquaintanceOnlineInformation;
		this._types[861] = FriendInformations;
		this._types[9348] = FriendOnlineInformations;
		this._types[8260] = FriendSpouseInformations;
		this._types[8676] = FriendSpouseOnlineInformations;
		this._types[2099] = IgnoredInformations;
		this._types[941] = IgnoredOnlineInformations;
		this._types[7492] = Contribution;
		this._types[4949] = GuildMemberInfo;
		this._types[3250] = HavenBagFurnitureInformation;
		this._types[9067] = GuildLogbookChestActivity;
		this._types[3398] = GuildLevelUpActivity;
		this._types[3935] = GuildPaddockActivity;
		this._types[2970] = GuildPlayerFlowActivity;
		this._types[8680] = GuildPlayerRankUpdateActivity;
		this._types[3270] = GuildRankActivity;
		this._types[7681] = GuildUnlockNewTabActivity;
		this._types[8590] = GuildLogbookEntryBasicInformation;
		this._types[5787] = RankPublicInformation;
		this._types[5578] = GuildRecruitmentInformation;
		this._types[8049] = HavenBagRoomPreviewInformation;
		this._types[8406] = AccountHouseInformations;
		this._types[4071] = HouseGuildedInformations;
		this._types[2374] = HouseInformations;
		this._types[409] = HouseInformationsForGuild;
		this._types[6977] = HouseInformationsForSell;
		this._types[2801] = HouseInformationsInside;
		this._types[3219] = HouseInstanceInformations;
		this._types[5255] = HouseOnMapInformations;
		this._types[6065] = InteractiveElement;
		this._types[7880] = InteractiveElementNamedSkill;
		this._types[2087] = InteractiveElementSkill;
		this._types[2952] = InteractiveElementWithAgeBonus;
		this._types[9518] = MapObstacle;
		this._types[3573] = SkillActionDescription;
		this._types[5684] = SkillActionDescriptionCollect;
		this._types[5905] = SkillActionDescriptionCraft;
		this._types[1078] = SkillActionDescriptionTimed;
		this._types[1041] = StatedElement;
		this._types[1570] = TeleportDestination;
		this._types[2736] = RecycledItem;
		this._types[8947] = StorageTabInformation;
		this._types[570] = UpdatedStorageTabInformation;
		this._types[6640] = EntityLook;
		this._types[5735] = IndexedEntityLook;
		this._types[9491] = SubEntity;
		this._types[5929] = ItemDurability;
		this._types[4446] = MountClientData;
		this._types[2137] = UpdateMountBooleanCharacteristic;
		this._types[470] = UpdateMountCharacteristic;
		this._types[5600] = UpdateMountIntegerCharacteristic;
		this._types[7825] = NuggetsBeneficiary;
		this._types[4252] = MountInformationsForPaddock;
		this._types[5612] = PaddockBuyableInformations;
		this._types[6426] = PaddockContentInformations;
		this._types[4294] = PaddockGuildedInformations;
		this._types[208] = PaddockInformations;
		this._types[5311] = PaddockInformationsForSell;
		this._types[4571] = PaddockInstancesInformations;
		this._types[2373] = PaddockItem;
		this._types[3299] = CharacterCharacteristicForPreset;
		this._types[6250] = EntitiesPreset;
		this._types[6253] = ForgettableSpellsPreset;
		this._types[4653] = FullStatsPreset;
		this._types[2553] = IconNamedPreset;
		this._types[5291] = ItemForPreset;
		this._types[4783] = ItemsPreset;
		this._types[3628] = Preset;
		this._types[5695] = PresetsContainerPreset;
		this._types[361] = SimpleCharacterCharacteristicForPreset;
		this._types[1457] = SpellForPreset;
		this._types[7774] = SpellsPreset;
		this._types[1993] = StatsPreset;
		this._types[7229] = AllianceInsiderPrismInformation;
		this._types[4594] = AlliancePrismInformation;
		this._types[9281] = PrismGeolocalizedInformation;
		this._types[65] = PrismInformation;
		this._types[6140] = AgressableStatusMessage;
		this._types[3538] = RankInformation;
		this._types[1831] = RankMinimalInformation;
		this._types[5117] = Shortcut;
		this._types[1189] = ShortcutEmote;
		this._types[3288] = ShortcutEntitiesPreset;
		this._types[8861] = ShortcutObject;
		this._types[2079] = ShortcutObjectItem;
		this._types[1697] = ShortcutObjectPreset;
		this._types[4118] = ShortcutSmiley;
		this._types[576] = ShortcutSpell;
		this._types[6837] = AbstractSocialGroupInfos;
		this._types[6340] = AllianceFactSheetInformation;
		this._types[9959] = ApplicationPlayerInformation;
		this._types[4014] = SocialApplicationInformation;
		this._types[2810] = SocialFight;
		this._types[2355] = SocialFightInfo;
		this._types[643] = GuildFactSheetInformations;
		this._types[9836] = GuildInsiderFactSheetInformations;
		this._types[2211] = SocialRecruitmentInformation;
		this._types[6817] = SocialEmblem;
		this._types[9920] = SocialMember;
		this._types[7527] = GameActionItem;
		this._types[8859] = SurrenderAccepted;
		this._types[8906] = SurrenderRefused;
		this._types[9548] = SurrenderRefusedBeforeTurn;
		this._types[2726] = SurrenderRefusedBeforeVote;
		this._types[8655] = SurrenderResponse;
		this._types[8687] = SurrenderVoteAccepted;
		this._types[1140] = SurrenderVoteRefused;
		this._types[8978] = SurrenderVoteRefusedAlreadyAsked;
		this._types[9709] = SurrenderVoteRefusedBeforeTurn;
		this._types[5188] = SurrenderVoteRefusedWaitBetweenVotes;
		this._types[3674] = SurrenderVoteResponse;
		this._types[8662] = Uuid;
		this._types[3311] = TrustCertificate;
		this._types[580] = Version;
		this._types[7749] = BufferInformation;

	}

	public static getInstance<T>(base: { new(): T }, typeId: number): T {
		let objType: { new(): T } = ProtocolTypeManager._types[typeId];
		if (!objType) {
			throw new Error("Type with id " + typeId + " is unknown.");
		}
		let obj: T = new objType();
		if (!(obj instanceof base)) {
			throw new Error("Type " + typeId + " is not a " + base + ".");
		}
		return obj;
	}

}